repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "50c5478ed9e10bf360335449280cf2a67f4edb7a"
    hooks:
      - id: prettier
        args: [--write]
        files: ^src/
        types_or: [javascript, jsx, ts, tsx, css]
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v14.4.0
    hooks:
      - id: stylelint
        files: ^src/
        types_or: [css]
        additional_dependencies:
          - stylelint@15.10.3
          - stylelint-config-prettier@9.0.5
          - stylelint-config-standard@34.0.0
          - stylelint-config-recommended@13.0.0
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "48f7d5347a35359ae8101c1cd76d9f80ef16355c"
    hooks:
      - id: eslint
        args: [--fix]
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - eslint@8.45.0
          - "@typescript-eslint/eslint-plugin@6.0.0"
          - "@typescript-eslint/parser@6.0.0"
          - eslint-config-prettier@9.0.0
